# Generated by Django 5.1.11 on 2025-07-28 17:15

import django_resized.forms
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='شرکت سازنده')),
                ('car_model', models.CharField(max_length=255, verbose_name='مدل')),
                ('cylinders', models.SmallIntegerField(choices=[(16, '16'), (12, '12'), (10, '10'), (8, '8'), (6, '6'), (5, '5'), (4, '4'), (3, '3')], verbose_name='تعداد سیلندر')),
                ('engine_type', models.CharField(choices=[('V', 'V (خورجینی)'), ('W', 'W'), ('i', 'inline(I) (خطی)'), ('Boxer', 'Boxer or Flat'), ('Wankle', 'Wankle'), ('Electric', 'Electric (برقی)'), ('Hybrid', 'Hybrid (هیبرید)')], max_length=10, verbose_name='نوع موتور')),
                ('transmission', models.CharField(choices=[('Manual', 'Manual(دستی)'), ('Automatic', 'Automatic (اتوماتیک)')], max_length=10, verbose_name='نوع گیربکس')),
                ('fuel_type', models.CharField(choices=[('Gas', 'Gasoline (بنزین)'), ('Diesel', 'Diesel (دیزل)'), ('Hybrid', 'Electricty - Gas (برق - بنزین)')], max_length=10, verbose_name='نوع سوخت')),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='حجم موتور (لیتر)')),
                ('drive_type', models.CharField(choices=[('RWD', 'Rear-Wheel-Drive (دیفرانسیل عقب)'), ('FWD', 'Front-Wheel-Drive (دیفرانسیل جلو)'), ('AWD', 'All-Wheel-Drive (4 چرخ محرک)'), ('4WD', '4-Wheel-Drive (4 چرخ محرک)')], max_length=3, verbose_name='نوع دیفرانسیل')),
                ('image_1', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to=website.models.Cars.saving_location, verbose_name='عکس 1')),
                ('image_2', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to=website.models.Cars.saving_location, verbose_name='عکس 2')),
                ('image_3', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to=website.models.Cars.saving_location, verbose_name='عکس 3')),
                ('details', models.TextField(blank=True, verbose_name='جزئیات')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('moified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Draft', 'Draft')], default='Draft', max_length=10, verbose_name='وضعیت')),
            ],
        ),
    ]
