# Generated by Django 5.1.11 on 2025-12-02 16:01

import Car.models
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('continent', models.CharField(max_length=15)),
                ('grand_prix', models.CharField(max_length=15)),
                ('circuit', models.CharField(max_length=50)),
                ('winner_name', models.CharField(max_length=40)),
                ('team', models.CharField(max_length=30)),
                ('time', models.TimeField()),
                ('laps', models.FloatField()),
                ('year', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='submittingNewCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255, verbose_name='Model')),
                ('cylinders', models.SmallIntegerField(choices=[(16, '16'), (12, '12'), (10, '10'), (8, '8'), (6, '6'), (5, '5'), (4, '4'), (3, '3')])),
                ('engine_type', models.CharField(choices=[('V', 'V'), ('W', 'W'), ('i', 'inline(I)'), ('Boxer', 'Boxer or Flat'), ('Wankle', 'Wankle'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=10, verbose_name='engine type')),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=10, verbose_name='transmission type')),
                ('fuel_type', models.CharField(choices=[('Gas', 'Gasoline'), ('Diesel', 'Diesel'), ('Hybrid', 'Electricty - Gas')], max_length=10, verbose_name='fuel type')),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='engine volume (Liters)')),
                ('drive_type', models.CharField(choices=[('RWD', 'Rear-Wheel-Drive'), ('FWD', 'Front-Wheel-Drive'), ('AWD', 'All-Wheel-Drive'), ('4WD', '4-Wheel-Drive')], max_length=3, verbose_name='drive type')),
                ('image_1', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to=Car.models.submittingNewCars.saving_location, verbose_name='image 1')),
                ('image_2', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to=Car.models.submittingNewCars.saving_location, verbose_name='image 2')),
                ('image_3', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to=Car.models.submittingNewCars.saving_location, verbose_name='image 3')),
                ('details', models.TextField(blank=True, verbose_name='description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('moified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Draft', 'Draft')], default='Draft', max_length=10, verbose_name='status')),
            ],
        ),
    ]
