# Generated by Django 5.1.11 on 2025-12-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula1',
            name='date',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='formula1',
            name='laps',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='formula1',
            name='time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='formula1',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
