# Generated by Django 5.1.11 on 2025-08-23 13:37

import django_resized.forms
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_model',
            field=models.CharField(max_length=255, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='cylinders',
            field=models.SmallIntegerField(choices=[(16, '16'), (12, '12'), (10, '10'), (8, '8'), (6, '6'), (5, '5'), (4, '4'), (3, '3')]),
        ),
        migrations.AlterField(
            model_name='cars',
            name='details',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='drive_type',
            field=models.CharField(choices=[('RWD', 'Rear-Wheel-Drive'), ('FWD', 'Front-Wheel-Drive'), ('AWD', 'All-Wheel-Drive'), ('4WD', '4-Wheel-Drive')], max_length=3, verbose_name='drive type'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='engine_type',
            field=models.CharField(choices=[('V', 'V'), ('W', 'W'), ('i', 'inline(I)'), ('Boxer', 'Boxer or Flat'), ('Wankle', 'Wankle'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=10, verbose_name='engine type'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='engine_volume',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='engine volume (Liters)'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='fuel_type',
            field=models.CharField(choices=[('Gas', 'Gasoline'), ('Diesel', 'Diesel'), ('Hybrid', 'Electricty - Gas')], max_length=10, verbose_name='fuel type'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='image_1',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to=website.models.Cars.saving_location, verbose_name='image 1'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='image_2',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to=website.models.Cars.saving_location, verbose_name='image 2'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='image_3',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to=website.models.Cars.saving_location, verbose_name='image 3'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='manufacturer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Draft', 'Draft')], default='Draft', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=10, verbose_name='transmission type'),
        ),
    ]
