# Generated by Django 5.1.11 on 2025-12-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_alter_formula1_date_alter_formula1_laps_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formula1',
        ),
    ]
