# Generated by Django 5.1.11 on 2025-12-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=11)),
                ('continent', models.CharField(max_length=15)),
                ('grand_prix', models.CharField(max_length=15)),
                ('circuit', models.CharField(max_length=50)),
                ('winner_name', models.CharField(max_length=40)),
                ('team', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=10)),
                ('laps', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
