# Generated by Django 5.1.11 on 2025-12-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formula1',
            new_name='Formula1Data',
        ),
    ]
