# Generated by Django 5.1.11 on 2025-12-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0002_rename_formula1_formula1data'),
    ]

    operations = [
        migrations.CreateModel(
            name='drivers',
            fields=[
                ('driver_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('ref_name', models.CharField(max_length=100)),
                ('number', models.PositiveSmallIntegerField(default=0, max_length=2)),
                ('code', models.CharField(max_length=3)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=60)),
            ],
        ),
    ]
