# Generated by Django 5.1.11 on 2025-12-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0003_drivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
