# Generated by Django 5.1.11 on 2025-12-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0004_alter_drivers_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formula1data',
            old_name='winner_name',
            new_name='winner_first_name',
        ),
        migrations.AddField(
            model_name='formula1data',
            name='winner_last_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
