# Generated by Django 5.1.11 on 2025-12-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0005_rename_winner_name_formula1data_winner_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formula1Data',
        ),
    ]
