# Generated by Django 5.1.11 on 2025-12-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0006_delete_formula1data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula1Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=11)),
                ('continent', models.CharField(max_length=15)),
                ('grand_prix', models.CharField(max_length=15)),
                ('circuit', models.CharField(max_length=50)),
                ('winner_first_name', models.CharField(max_length=40)),
                ('winner_last_name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=30)),
                ('time', models.TimeField(max_length=10)),
                ('laps', models.SmallIntegerField(max_length=5)),
            ],
        ),
    ]
