# Generated by Django 5.1.11 on 2025-12-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0007_formula1data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula1data',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='formula1data',
            name='laps',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='formula1data',
            name='time',
            field=models.TimeField(),
        ),
    ]
