# Generated by Django 5.1.11 on 2025-12-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0008_alter_formula1data_date_alter_formula1data_laps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula1data',
            name='time',
            field=models.DurationField(),
        ),
    ]
