# Generated by Django 5.1.11 on 2025-12-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0009_alter_formula1data_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='circuits',
            fields=[
                ('circuit_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ref_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='drivers',
            name='driver_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
