# Generated by Django 5.1.11 on 2025-12-15 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0010_circuits_alter_drivers_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuits',
            name='circuit_id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='driver_id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='races',
            fields=[
                ('race_id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('race_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('fp1_date', models.DateField(blank=True, null=True)),
                ('fp1_time', models.TimeField(blank=True, null=True)),
                ('circuit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='Formula1.circuits')),
            ],
        ),
    ]
