# Generated by Django 5.1.11 on 2025-12-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0011_alter_circuits_circuit_id_alter_drivers_driver_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='races',
            name='fp2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='races',
            name='fp2_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='races',
            name='fp3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='races',
            name='fp3_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='races',
            name='quali_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='races',
            name='quali_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='races',
            name='sprint_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='races',
            name='sprint_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
