# Generated by Django 5.1.11 on 2025-12-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0012_races_fp2_date_races_fp2_time_races_fp3_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula1data',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='races',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
