# Generated by Django 5.1.11 on 2025-12-16 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0013_formula1data_year_races_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races',
            name='circuit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='races', to='Formula1.circuits'),
        ),
        migrations.CreateModel(
            name='driverStandings',
            fields=[
                ('ds_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('points', models.SmallIntegerField()),
                ('position', models.SmallIntegerField()),
                ('wins_in_season', models.SmallIntegerField()),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='season_driver_standing', to='Formula1.drivers')),
                ('race_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='season_driver_standing', to='Formula1.races')),
            ],
        ),
    ]
