# Generated by Django 5.1.11 on 2025-12-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0014_alter_races_circuit_id_driverstandings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverstandings',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='driverstandings',
            old_name='race_id',
            new_name='race',
        ),
        migrations.RenameField(
            model_name='races',
            old_name='circuit_id',
            new_name='circuit',
        ),
    ]
