# Generated by Django 5.1.11 on 2025-12-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0015_rename_driver_id_driverstandings_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='constructors',
            fields=[
                ('constructor_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ref_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=30)),
            ],
        ),
    ]
