# Generated by Django 5.1.11 on 2025-12-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0020_alter_results_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverstandings',
            old_name='driver',
            new_name='driver_id',
        ),
        migrations.RenameField(
            model_name='driverstandings',
            old_name='race',
            new_name='race_id',
        ),
        migrations.RenameField(
            model_name='races',
            old_name='circuit',
            new_name='circuit_id',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='constructor',
            new_name='constructor_id',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='driver',
            new_name='driver_id',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='race',
            new_name='race_id',
        ),
    ]
