# Generated by Django 5.1.11 on 2025-12-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0021_rename_driver_driverstandings_driver_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races',
            name='race_number',
            field=models.PositiveIntegerField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='top_speed_of_fl',
            field=models.FloatField(verbose_name='fastest lap top speed'),
        ),
    ]
