# Generated by Django 5.1.11 on 2025-12-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0022_alter_races_race_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuits',
            name='circuit_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='constructor_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='driver_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driverstandings',
            name='ds_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='races',
            name='race_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='races',
            name='race_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='results',
            name='result_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
