# Generated by Django 5.1.11 on 2025-12-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0023_alter_circuits_circuit_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='races',
            old_name='date',
            new_name='race_date',
        ),
        migrations.RenameField(
            model_name='races',
            old_name='sprint_time',
            new_name='race_time',
        ),
        migrations.RenameField(
            model_name='races',
            old_name='sprint_date',
            new_name='sprint_race_date',
        ),
        migrations.RenameField(
            model_name='races',
            old_name='time',
            new_name='sprint_race_time',
        ),
        migrations.AddField(
            model_name='races',
            name='sprint_quali_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='races',
            name='sprint_quali_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
