# Generated by Django 5.1.11 on 2025-12-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0024_rename_date_races_race_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='races',
            old_name='race_number',
            new_name='round',
        ),
    ]
