# Generated by Django 5.1.11 on 2026-01-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0025_rename_race_number_races_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
