# Generated by Django 5.1.11 on 2026-01-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0026_alter_drivers_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='code',
            field=models.CharField(max_length=3),
        ),
    ]
