# Generated by Django 5.1.11 on 2026-01-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0027_alter_drivers_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races',
            name='race_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
