# Generated by Django 5.1.11 on 2026-01-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0029_alter_circuits_altitude_alter_circuits_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circuits',
            options={'verbose_name': 'circuit', 'verbose_name_plural': 'circuits'},
        ),
        migrations.AlterModelOptions(
            name='constructors',
            options={'verbose_name': 'constructor', 'verbose_name_plural': 'constructors'},
        ),
        migrations.AlterModelOptions(
            name='drivers',
            options={'verbose_name': 'driver', 'verbose_name_plural': 'drivers'},
        ),
        migrations.AlterModelOptions(
            name='driverstandings',
            options={'verbose_name': 'driver standing', 'verbose_name_plural': 'driver standings'},
        ),
        migrations.AlterModelOptions(
            name='races',
            options={'verbose_name': 'race', 'verbose_name_plural': 'races'},
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
        migrations.AlterField(
            model_name='races',
            name='fp1_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
