# Generated by Django 5.1.11 on 2026-01-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1', '0030_alter_circuits_options_alter_constructors_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races',
            name='fp1_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
